data/com.github.sgpthomas.hourglass.appdata.xml
Fixes https://appstream.elementary.io/appcenter/html/xenial/main/issues/com.github.sgpthomas.hourglass.html
=> Remove "." from appdata summary

data/com.github.sgpthomas.hourglass.appdata.xml.in, debian/changelog, meson.build
=> Release 1.2.0

src/Dialogs/NewAlarmDialog.vala
=> Don't reset repeat setting on closing popover

src/Daemon/HourglassServer.vala, src/Services/DBusManager.vala, src/Widgets/AlarmTimeWidget.vala, src/Widgets/Counter.vala
There were many warnings about unhandled `GLib.IOError` and `GLib.DBusError`. This PR resolves this.
=> Handle unhandled errors

src/Daemon/NotificationManager.vala
=> Fix notification icon is not set

src/Daemon/AlarmManager.vala, src/Daemon/HourglassDaemon.vala, src/Daemon/NotificationManager.vala
- Explicit namespace instead of `using`
- Less scope for `alarm_list`
- Lint using [vala-lint](https://github.com/vala-lang/vala-lint)
- Namespace as a part of a class name
=> Daemon: Fix coding style

src/Hourglass.vala
- Lint using [vala-lint](https://github.com/vala-lang/vala-lint)
=> HourglassApp: Fix coding style

schemas/com.github.sgpthomas.hourglass.gschema.xml, src/Widgets/Counter.vala, src/Widgets/TimerTimeWidget.vala
=> Fixed left time shows unexpected values if set time is too big

src/Hourglass.vala, src/Window/MainWindow.vala
- Remove unused argument `app`
- Bump copyright
- Explicit namespace instead of `using`
- Lint using [vala-lint](https://github.com/vala-lang/vala-lint)
- Namespace as a part of a class name
- Signals in the top
- Remove redundant comments
- Less scope: make variables local if possible
- Fix a long line
=> MainWindow: Fix coding style

src/Daemon/AlarmManager.vala, src/Daemon/HourglassDaemon.vala, src/Daemon/HourglassServer.vala, src/Dialogs/NewAlarmDialog.vala, src/Hourglass.vala, src/Services/DBusManager.vala, src/Services/StyleManager.vala, src/Widgets/AlarmTimeWidget.vala, src/Widgets/TimerTimeWidget.vala
The log message happen to appear unintentionally in the prompt on Terminal, which is frustrating
=> Show debug message with debug method

data/style/elements.css
=> Add :disabled pseudo-class to the .round-button class

src/Widgets/AlarmTimeWidget.vala
=> Use icons for add/remove buttons

src/Widgets/Alarm.vala
- Explicit namespace instead of `using` directive
- Inline namespace
- GObject-style construction if possible
- Use `=` instead of `set_*` methods
- Add indentation in `if`-`else` conditions
=> Alarm: Clean code

.github/workflows/main.yml, README.md, meson.build, src/Dialogs/NewAlarmDialog.vala
Fixes #109
This will be compatible with odin or later
=> NewAlarmDialog: Replace Gtk.Dialog with Granite.Dialog

.gitignore, com.github.sgpthomas.hourglass.yml
=> Add Flatpak manifest

com.github.sgpthomas.hourglass.yml
=> Fix libcanberra version to 0.30

data/com.github.sgpthomas.hourglass.appdata.xml.in
=> appdata: Add OARS and launchable tag

data/style/text.css, src/Widgets/Alarm.vala
=> Alarm: Use bigger font

src/Window/MainWindow.vala
=> MainWindow: Respect an elementary OS-wide dark preference

data/com.github.sgpthomas.hourglass-daemon.desktop.in.in, data/com.github.sgpthomas.hourglass.desktop.in.in, meson.build, src/Config.vala.in, src/Hourglass.vala, src/Window/MainWindow.vala
Also replace extra constants while we're here
=> Fix translations are not loaded in Flatpak

src/Widgets/TimerTimeWidget.vala
=> TimerTimeWidget: Save the current timer only when timer stopped/ended

src/Widgets/TimerTimeWidget.vala
=> TimerTimeWidget: Add Reset button

src/Widgets/AlarmTimeWidget.vala, src/Widgets/StopwatchTimeWidget.vala, src/Widgets/TimeWidget.vala, src/Widgets/TimerTimeWidget.vala, src/Window/MainWindow.vala
Use GObject construction and DRY
=> Make TimeWidget an abstract class

src/Widgets/AlarmTimeWidget.vala, src/Widgets/TimeWidget.vala
Seems like setting property using GObject does not work in abstract class
=> Fix orientation is not applied as expected

src/Widgets/TimerTimeWidget.vala
=> TimerTimeWidget: Support setting purpose of a timer

schemas/com.github.sgpthomas.hourglass.gschema.xml
=> Less width by default

src/Daemon/AlarmManager.vala
=> Fix repeating alarms can't be disabled

src/Daemon/AlarmManager.vala, src/Daemon/HourglassDaemon.vala
=> Notify on every 0 second

src/Daemon/AlarmManager.vala
=> Keep alarm on even after it rings

README.md, data/com.github.sgpthomas.hourglass.desktop.in.in, schemas/com.github.sgpthomas.hourglass.gschema.xml, src/Daemon/AlarmManager.vala, src/Daemon/HourglassDaemon.vala, src/Daemon/HourglassServer.vala, src/Daemon/NotificationManager.vala, src/Daemon/meson.build, src/Services/DBusManager.vala, src/Views/TimerView.vala, src/Widgets/Counter.vala
=> Use GLib.Notification

src/Widgets/Alarm.vala
=> Fix a regression that alarm is not refreshed on change

com.github.sgpthomas.hourglass.yml
=> Flatpak: No longer require libcanberra

src/Daemon/AlarmManager.vala, src/Dialogs/NewAlarmDialog.vala, src/Widgets/Alarm.vala
=> Optional date

src/Window/MainWindow.vala
=> Make sure to iconify always when the timer is active

src/Views/StopwatchView.vala, src/Views/TimerView.vala, src/Widgets/Counter.vala
- Use properties if possible
- Naming conventions
=> Counter: Clean Code

COPYING, src/Daemon/AlarmManager.vala, src/Daemon/HourglassDaemon.vala, src/Daemon/HourglassServer.vala, src/Daemon/NotificationManager.vala, src/Dialogs/MultiSelectPopover.vala, src/Dialogs/NewAlarmDialog.vala, src/Hourglass.vala, src/Objects/Counter.vala, src/Services/DBusManager.vala, src/Utils.vala, src/Views/AbstractView.vala, src/Views/AlarmView.vala, src/Views/StopwatchView.vala, src/Views/TimerView.vala, src/Widgets/Alarm.vala, src/Widgets/TimeSpinner.vala, src/Window/MainWindow.vala
* COPYING: Fix whitespace/indentation and use `https` for URLs
* Sources: Use SPDX License Headers
=> Update copyright texts

data/Application.css, data/com.github.sgpthomas.hourglass.appdata.xml.in, src/Dialogs/NewAlarmDialog.vala, src/Views/StopwatchView.vala, src/Views/TimerView.vala
Officially guaranteed to look good on both light/dark style. Also this should keep consistence with other elementary or curated apps.
=> Use palette of elementary for branding color

src/Widgets/Alarm.vala
=> Alarm: Organize displayed information

src/Dialogs/NewAlarmDialog.vala
Instead of manually connecting to each button
=> NewAlarmDialog: Use Gtk.Dialog.response

data/com.github.sgpthomas.hourglass.metainfo.xml.in, data/meson.build
- Correct copyright info
- Correct the project license to GPL 3.0+, as you can see in [the previous code](https://github.com/sgpthomas/hourglass/blob/bda256c9aca6d5d71090e203b279f3777ddcb16d/src/Hourglass.vala#L1-L17)
- Use freedesktop.org's tag `branding` and `supports`
=> Metainfo: Rename and improve

src/Views/StopwatchView.vala
=> StopwatchView: Ctrl+S to toggle

po/extra/ru.po, po/ru.po
I totally forgot about this :sweat_smile:
=> Update extra Russian translation

src/Views/AlarmView.vala
We can use this useful function instead of switching views manually by Gtk.Stack
=> AlarmView: Use Gtk.ListBox.set_placeholder

src/Dialogs/MultiSelectPopover.vala, src/Dialogs/NewAlarmDialog.vala, src/Views/AlarmView.vala, src/Views/TimerView.vala, src/Widgets/Alarm.vala, src/Window/MainWindow.vala
[Gtk.StyleContext.add_class](https://valadoc.org/gtk4/Gtk.StyleContext.add_class.html) has been deprecated since 4.10
=> Use Gtk.Widget.add_css_class () instead of deprecated Gtk.StyleContext.add_class ()
